spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 123456

  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /root_hosts
    username: root
    password: 123456
    publisher-confirms: true
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          # 最大尝试次数
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
          stateless: true


  #mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
    #\u5B9E\u4F53\u626B\u63CF\uFF0C\u591A\u4E2Apackage\u7528\u9017\u53F7\u6216\u8005\u5206\u53F7\u5206\u9694
  typeAliasesPackage: com.example.mall.entity
  typeEnumsPackage: com.example.mall.enums.*
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
    sql-parser-cache: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

eureka:
  client:
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    registerWithEureka: false
    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetchRegistry: false

#业务系统前缀
business:
  #feign的url配置
  feign: